swagger: "2.0"
info:
  version: "1.0.0"
  title: "Demo API"
basePath: "/"
schemes:
  - https
paths:
  /:
    get:
      summary: "Perform a health check of the API"
      security: []
      responses:
        "200":
          description: "OK"
  /credit-check:
    post:
      summary: "Perform a credit check"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "The company details"
          required: true
          schema:
            $ref: "#/definitions/CreditCheck"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Result"
        "405":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
        - basic_auth: []
securityDefinitions:
  basic_auth:
    type: basic
definitions:
  CreditCheck:
    type: "object"
    properties:
      referenceId:
        type: "string"
      companyId:
        type: "string"
  Result:
    type: "object"
    properties:
      referenceId:
        type: "string"
      checks:
        type: "array"
        items:
          $ref: "#/definitions/Check"
  Check:
    type: "object"
    properties:
      text:
        type: "string"
      weight:
        type: "integer"
      freeFormatOutcome:
        type: "string"
      genericOutcome:
        $ref: "#/definitions/Outcome"
      specificOutcome:
        $ref: "#/definitions/Outcome"
  ErrorResponse:
    type: "object"
    properties:
      code:
        type: "string"
      message:
        type: "string"
      innerErrors:
        type: "array"
        items:
          $ref: "#/definitions/InnerError"
  InnerError:
    type: "object"
    properties:
      message:
        type: "string"
      target:
        type: "string"
  Outcome:
    type: string
    enum:
      - Compensator
      - Approved
      - Compensated
      - Denied